-- Answers to Exercise 7 here
DROP TABLE IF EXISTS dwc1_article_comments;

CREATE TABLE IF NOT EXISTS dwc1_article_comments (
  Comm_num INT AUTO_INCREMENT,
  article_num INT,
  comm_text text,
  PRIMARY KEY (Comm_num),
  FOREIGN KEY (article_num) REFERENCES dwc1_articles (article_num)
);


INSERT INTO dwc1_article_comments (article_num, comm_text) VALUES (3,'Maecenas placerat, ex eget vehicula suscipit, tortor ante fermentum libero, vel ultrices lacus tortor vitae sapien. Morbi tempus efficitur dui, vel varius quam fermentum eu. Suspendisse fermentum leo ut felis dignissim, vel vestibulum augue bibendum. Nullam congue venenatis dolor ac pretium. Integer non tincidunt tellus. Ut euismod mollis ligula vitae aliquam. Ut aliquam justo eu elit suscipit blandit. Aenean ornare diam ut lectus facilisis maximus. Aenean tempus pellentesque erat, nec fermentum augue pretium non. Pellentesque et est molestie, dignissim orci in, mattis nunc. Aliquam congue pharetra nulla, sit amet tempus libero sodales in. Morbi interdum, metus id cursus egestas, tellus metus tristique nulla, at ullamcorper erat tortor rhoncus sapien. Praesent odio massa, sagittis sed euismod in, vestibulum at diam. Integer eu ante vitae ligula aliquet fringilla. Sed pulvinar augue felis, quis pharetra libero accumsan sed. Fusce consequat aliquet risus.'),
                                                                  (5,'Nulla dignissim nulla sed egestas porttitor. Vivamus sit amet metus eget mauris aliquet posuere a vel dolor. Pellentesque laoreet eget dolor eu feugiat. Maecenas nec ipsum a sapien tincidunt pretium eget at tellus. Morbi tempus diam eget elit porttitor, id rutrum erat tristique. Vivamus eleifend sapien a nibh imperdiet pretium. Proin nisl est, rutrum ut neque vel, cursus tincidunt est. Maecenas volutpat vel sapien id sagittis. Ut ipsum ipsum, tincidunt a enim id, malesuada pulvinar purus. Pellentesque elementum maximus tempor.'),
                                                                  (7,'Aenean vitae lacus a sem laoreet dignissim a eget risus. Donec facilisis vestibulum mauris ac pellentesque. Aliquam ullamcorper, risus vitae egestas fringilla, nulla quam rutrum dolor, a iaculis ex sem et mi. Ut eu ex placerat, tincidunt neque quis, luctus purus. Mauris mollis bibendum neque eu venenatis. Vestibulum et bibendum ligula. Maecenas eget dolor semper, suscipit quam sit amet, viverra neque. Phasellus hendrerit diam enim, nec tempus nulla molestie ac.'),
                                                                  (3,'Phasellus enim ligula, sagittis sit amet augue sed, pharetra vehicula neque. Proin et purus in justo ultricies efficitur tempus vel neque. Nullam imperdiet quam eget euismod imperdiet. Vivamus convallis dolor in hendrerit eleifend. Praesent ut leo orci. Cras id lectus vel augue blandit rutrum sed non tortor. Mauris convallis quis purus vitae lacinia. Donec dapibus ipsum in urna dictum, ut semper velit volutpat. Donec posuere, tellus ut lacinia volutpat, nisl lectus eleifend lorem, eget malesuada metus nisl at turpis. Quisque ut ante urna. Curabitur elementum nisi ante, in sollicitudin orci tempor sit amet. Fusce eget risus dui. Nulla quis sollicitudin erat. Proin consectetur eros vitae malesuada ultrices.'),
                                                                  (2,'Duis suscipit ante in erat vestibulum congue. Vivamus sollicitudin libero turpis, at laoreet turpis lacinia ac. Suspendisse egestas ut lacus eu maximus. Integer fringilla sagittis arcu non semper. Aenean commodo nisl accumsan, dapibus nisi ac, iaculis nibh. Nunc molestie laoreet est. Cras nunc erat, hendrerit a vulputate eu, porttitor eget lacus. Sed maximus dapibus tincidunt. Phasellus luctus fermentum nisi non vulputate. Suspendisse lobortis molestie quam eu molestie. Sed at ligula et metus dapibus aliquet quis nec magna. Maecenas placerat ante quis est auctor eleifend. Suspendisse mi nisi, aliquam in hendrerit at, tincidunt quis risus.'),
                                                                  (4,'Quisque id erat quis sapien faucibus interdum. Nulla et finibus lorem, vel posuere tortor. Nunc ac ipsum eget turpis molestie lacinia. Donec consectetur tincidunt elit, convallis dapibus risus fermentum et. Sed et nisl blandit libero fermentum finibus. Nullam dictum lacinia placerat. Vestibulum rutrum lorem a orci scelerisque maximus. Aenean sed cursus lorem, tincidunt volutpat massa. Pellentesque sit amet felis sodales, fermentum elit in, dictum risus.'),
                                                                  (3,'Phasellus eget luctus dolor, ut facilisis lectus. Nam hendrerit cursus nisi, hendrerit scelerisque risus maximus eu. Donec et commodo nulla. Vestibulum bibendum arcu arcu, sit amet pellentesque tellus euismod a. Phasellus blandit mauris a risus vestibulum commodo. Nullam aliquam mi volutpat porta consectetur. Suspendisse faucibus euismod ipsum, eget faucibus urna gravida sed. Nullam gravida neque in elit imperdiet, eu finibus felis bibendum. Aliquam semper consequat molestie.'),
                                                                  (7,'Cras viverra elementum rutrum. Mauris venenatis sagittis tellus eu vehicula. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed vel dictum magna, a scelerisque felis. Nam risus velit, condimentum sed gravida sed, semper non ante. Nullam ut lacus ut nunc tempus facilisis. Cras sodales rutrum auctor. In hendrerit dui at neque rhoncus commodo. Donec facilisis rutrum fringilla. Sed hendrerit rhoncus arcu at finibus. Sed pharetra lorem tellus, ut eleifend ante lacinia vel. Praesent mattis dui quis dolor imperdiet, sit amet pretium lacus tincidunt. Curabitur auctor eget nunc nec viverra. Nam eu augue vitae magna sagittis luctus. Nulla condimentum rhoncus est vel aliquet. Quisque a condimentum lacus.'),
                                                                  (1,'Maecenas vehicula mi eu purus tincidunt luctus. Sed cursus tempus finibus. Aliquam maximus dui ac risus mattis, ut sodales diam venenatis. Donec maximus eu sem non fermentum. Ut sodales tincidunt ex sit amet aliquet. Fusce mattis tortor blandit, iaculis lorem vel, consequat ligula. Sed tellus mi, rhoncus ornare rhoncus bibendum, tincidunt et sapien. Donec eu nunc nec lacus pretium dignissim. Aenean dignissim velit mi.'),
                                                                  (5,'Pellentesque euismod ligula sed velit auctor malesuada. Fusce tempor urna vel pharetra varius. Integer condimentum ut leo in sagittis. Mauris ipsum augue, vehicula id placerat et, consequat ac orci. Duis et quam tortor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Suspendisse eget ex eget mauris sodales laoreet. Donec orci metus, cursus et nunc sit amet, efficitur consequat ipsum. Curabitur magna nisi, euismod a mi a, consectetur hendrerit dui. Aliquam eget elementum metus. Morbi vel dui massa. Duis sollicitudin mi justo, posuere rhoncus lacus semper ac. Sed sodales lorem ut mauris venenatis consequat. Phasellus finibus at odio vel congue. Nulla cursus, lorem at ultrices malesuada, arcu nisi pretium neque, sit amet consequat erat lacus ac libero.'),
                                                                  (4,'Vestibulum vel suscipit tellus. Maecenas rhoncus luctus quam, non elementum arcu euismod et. Fusce pretium mollis eros, at condimentum nunc tempus bibendum. Cras ipsum lorem, egestas ac molestie eget, auctor nec odio. Donec at dapibus augue. Nulla scelerisque, nunc non convallis tempor, eros ante iaculis diam, nec vestibulum magna nisi dictum mi. Nam lacinia fringilla lacus non facilisis. Sed sit amet molestie nunc, et malesuada ligula. Etiam malesuada, odio et ultricies convallis, orci risus mattis ante, id tristique sapien velit viverra magna. Etiam sapien est, facilisis ut molestie id, volutpat pellentesque metus. Mauris nibh nunc, elementum vitae tortor vel, efficitur finibus eros. Nam ligula velit, imperdiet at ultrices eu, pulvinar at tellus. Pellentesque a accumsan nisi. Maecenas eu lacinia augue, tincidunt auctor lectus.'),
                                                                  (4,'Morbi imperdiet nibh ac sapien sodales, nec iaculis dui pellentesque. Ut imperdiet consequat nunc. Duis mattis ligula sed tempor suscipit. Vivamus vel vehicula urna. Aenean dapibus venenatis lectus vel consequat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras quis semper eros. Mauris ornare accumsan lectus id malesuada. Nullam sed efficitur justo. Ut vestibulum augue eu nulla semper, pharetra accumsan ante egestas. Integer vitae finibus dolor. Sed finibus lacus sed dolor venenatis, ac consectetur dui tincidunt.'),
                                                                  (2,'Curabitur blandit congue nulla, eu maximus lorem tristique eget. Nullam a ipsum posuere, egestas quam at, aliquet lorem. Praesent ullamcorper quam id purus blandit posuere. Vestibulum ex arcu, rhoncus consectetur dolor ac, viverra faucibus mi. Nunc in congue lorem, at suscipit leo. Donec vitae pulvinar mi. Nam mauris ante, iaculis non enim ut, congue malesuada lectus. Sed vitae felis risus. Pellentesque sagittis eros urna, et elementum ligula condimentum pulvinar. Pellentesque ut facilisis lorem, nec molestie orci. Mauris ac turpis scelerisque, fringilla arcu sit amet, semper diam. Vivamus tempor iaculis urna. Suspendisse ac leo condimentum, tincidunt magna vitae, ultricies nunc. Duis at justo eget turpis bibendum lobortis eu vel neque. Nullam dignissim nunc sem, a congue ipsum mattis ut. Nunc et pellentesque eros, eget condimentum dolor.'),
                                                                  (4,'Duis eget vestibulum lacus. Curabitur tincidunt, turpis eu ullamcorper vehicula, ex diam aliquet velit, vel pulvinar dui ante sed nibh. Aliquam ex ante, iaculis volutpat auctor vitae, sodales a metus. Duis ornare sapien id lorem iaculis, ac vestibulum tellus lobortis. Sed sapien elit, vestibulum sit amet efficitur sed, ullamcorper eu erat. Sed ac dolor et tellus dignissim vestibulum. Fusce pulvinar ligula vitae tellus rutrum, sit amet auctor magna suscipit. Nam ut mattis mauris. Quisque volutpat erat massa, a aliquam orci tristique vitae. Vivamus sit amet blandit ligula.'),
                                                                  (8,'Proin euismod sem ex, convallis convallis lacus facilisis at. Aliquam finibus semper elementum. Sed ac dolor id libero suscipit laoreet ut eu sem. Ut non tincidunt sem. Nulla sed lacus sit amet felis eleifend lobortis. Nam placerat magna ut lectus congue, sed volutpat ligula facilisis. Maecenas pellentesque porta egestas. Sed et rhoncus lacus. Curabitur eget enim mollis, eleifend lorem at, accumsan velit.'),
                                                                  (6,'Praesent vel dictum augue. Nunc porta iaculis interdum. Duis accumsan dapibus pulvinar. Nunc eu eros aliquet felis bibendum accumsan. Pellentesque venenatis ullamcorper nulla, quis tincidunt libero elementum vel. Morbi ut ante vitae ex molestie lacinia. Sed malesuada mi a leo pellentesque, fermentum dapibus urna accumsan. Cras ut rutrum orci. Etiam imperdiet iaculis lectus. Praesent feugiat orci id purus congue, eget blandit ligula finibus. Proin sed ipsum feugiat, porta lorem quis, dictum ex. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Morbi interdum, dolor id commodo pulvinar, dolor magna finibus mauris, ut imperdiet massa mi eu elit. Duis sodales aliquet maximus. In rutrum pretium erat nec rhoncus.'),
                                                                  (8,'Sed aliquam elementum tellus, a convallis massa ullamcorper ac. Mauris vitae volutpat quam. Vivamus ante erat, consequat et lectus sed, eleifend sagittis ante. Proin fermentum fermentum erat, non hendrerit lectus gravida a. In hac habitasse platea dictumst. Nam at purus scelerisque metus porta consectetur at vel nunc. Cras semper felis at velit semper posuere. Proin lectus est, interdum ac interdum nec, porta a nibh. Praesent sit amet vestibulum odio, quis gravida lacus. Aliquam sit amet malesuada dolor, ultrices porta tortor. Curabitur molestie sagittis est, vel rhoncus nulla tempus nec. Aliquam rutrum ligula feugiat, maximus eros quis, finibus augue. Aenean sagittis, elit vel sollicitudin mollis, purus justo pharetra odio, vel mattis augue metus quis velit. Curabitur varius et lacus eu maximus. Fusce sed scelerisque erat, at sollicitudin libero.'),
                                                                  (5,'Suspendisse condimentum egestas sollicitudin. Sed maximus enim massa, nec egestas sapien ultrices eget. Nullam eget ex et magna venenatis laoreet sed sit amet enim. Sed in aliquam felis. Phasellus semper tellus at mi elementum sollicitudin. Nulla consectetur sapien sit amet erat tincidunt tempor. Suspendisse potenti. Nunc in aliquet nunc, vel rhoncus diam. Mauris varius id turpis nec pellentesque. Aliquam ut malesuada lorem, quis auctor justo. Ut porttitor varius commodo.'),
                                                                  (7,'In in purus quis turpis dapibus convallis et ac ante. Nullam nec nisi vel diam tristique sodales quis nec justo. In vitae efficitur tellus, et ullamcorper lorem. Nullam eget ante a odio bibendum semper. Vivamus non aliquet eros. Ut egestas blandit finibus. Sed auctor bibendum sem, ut ultrices quam pharetra molestie. Phasellus justo orci, placerat a mattis sit amet, commodo at leo. Mauris pulvinar risus dapibus porta tincidunt. Aenean congue aliquet diam vel bibendum. Duis euismod sagittis molestie. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam bibendum laoreet nulla, vitae pulvinar libero rhoncus quis. Nulla dictum lorem id enim tempus, faucibus hendrerit nisi tristique.'),
                                                                  (1,'Proin consectetur ante quis dolor mollis vestibulum. Suspendisse eget nunc eros. Mauris interdum sem sed leo hendrerit, ut luctus nibh mollis. Donec pretium dolor id diam facilisis hendrerit. Cras et nisl odio. Pellentesque eget sem nec ante bibendum aliquet a sed nisl. Aenean tortor neque, egestas malesuada nibh nec, venenatis congue nisl. Praesent feugiat nisi vitae placerat ullamcorper. Mauris ac purus ultricies, condimentum magna at, facilisis arcu. Duis non odio in dolor laoreet vestibulum vitae sed neque. Nam vestibulum sapien nisl, interdum egestas purus condimentum id.');