-- Answers to Exercise 4 here
DROP TABLE IF EXISTS dwc1_articles;

CREATE TABLE IF NOT EXISTS dwc1_articles (
  article_num INT AUTO_INCREMENT,
  article_title varchar(200),
  article_text TEXT,
  PRIMARY KEY (article_num)
);

INSERT INTO dwc1_articles (article_title, article_text) VALUES ('Lorem ipsum dolor sit amet.','Quisque consectetur auctor sollicitudin. Nullam ac ornare nulla, ut convallis lacus. Ut orci ex, interdum eu posuere nec, tempor a nisi. Nunc et mollis ligula. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla sed arcu est. Morbi cursus ligula ipsum, ut consectetur nunc blandit ac. Fusce elit odio, placerat ut facilisis eleifend, suscipit vitae nulla. Praesent interdum placerat est eget accumsan. Proin eget ultrices elit. Suspendisse est tortor, varius a eleifend placerat, aliquam nec nibh.'),
                                                               ('Phasellus at risus fermentum, dapibus.','Duis facilisis pretium turpis, sagittis interdum eros mattis eget. Suspendisse potenti. Praesent semper, eros in maximus varius, ante lectus mollis velit, id laoreet risus dui et nibh. Aenean tempor nibh dolor, vel faucibus tellus venenatis vel. Nulla aliquam gravida ex, quis venenatis nisl malesuada sed. Mauris imperdiet posuere sapien nec tristique. Maecenas luctus velit quis nisi finibus, non pretium ex elementum. Sed pharetra, neque quis auctor vestibulum, orci velit feugiat erat, ut vehicula dolor ligula in purus. Donec fermentum elit eget ante consectetur, quis rutrum enim rhoncus. Vivamus eleifend, justo nec facilisis ultricies, diam nibh fringilla augue, non suscipit justo metus non enim. Suspendisse potenti. Integer eleifend nisi quis metus laoreet, vestibulum tempor ante iaculis. Sed ultrices bibendum turpis, ut blandit nulla egestas vel. Nullam accumsan vel lectus vel imperdiet.'),
                                                               ('Aliquam a aliquam libero, eu.','Vestibulum vel tincidunt eros. Proin suscipit tempor porta. Etiam a sodales est, non auctor erat. In placerat ante id nulla fermentum accumsan. Praesent sit amet malesuada ante, sed pulvinar est. Donec faucibus magna lectus, ac faucibus sem commodo in. Proin dictum vitae nulla sed porttitor. Vivamus rhoncus leo eget fringilla auctor. Vivamus aliquam placerat sapien. Fusce vel nunc congue, congue ipsum in, mattis dui.'),
                                                               ('Nulla quis diam tincidunt, mollis.','Nulla est odio, hendrerit id eros ac, maximus molestie odio. Praesent enim risus, eleifend vel neque vulputate, tristique malesuada tellus. In nibh leo, egestas eu lectus eget, malesuada blandit ligula. Quisque finibus hendrerit leo, non ullamcorper sem suscipit ac. Nunc finibus justo quis odio imperdiet, vitae pretium mauris molestie. Vestibulum eu sodales augue, ornare tempus nisi. Sed in massa orci. Nunc tincidunt elit eget placerat fermentum.'),
                                                               ('Quisque egestas magna vel nunc.','Nulla varius lectus ac condimentum condimentum. Aenean nunc quam, convallis pharetra nunc facilisis, auctor dignissim ante. Phasellus porttitor vestibulum nunc, eu facilisis purus. Ut viverra imperdiet metus a mollis. Vivamus laoreet ante a enim ultrices, sed lacinia ipsum vehicula. Etiam consequat lacus sed posuere auctor. Praesent at efficitur dolor, at ultrices purus. Mauris turpis lorem, placerat sit amet posuere iaculis, fringilla et ligula. Aliquam pretium, purus at sagittis scelerisque, nisl sem venenatis neque, rhoncus elementum turpis leo vitae felis. Donec tortor libero, feugiat eu faucibus et, rhoncus eu leo. Sed vitae quam id tortor eleifend gravida vel et orci. Nam vel erat ullamcorper leo aliquet ornare ac non tortor. Nunc pulvinar dolor eget dui convallis facilisis. Fusce suscipit risus vel elit ornare, nec varius nisi sollicitudin.'),
                                                               ('Nunc sed eros mi. Integer.','Ut ultricies lectus porttitor suscipit euismod. Etiam tincidunt ipsum in tortor iaculis cursus. Etiam ornare, nisl non egestas iaculis, neque diam rhoncus ante, non fermentum erat magna vehicula justo. Ut sed mauris ut sapien laoreet mollis. Suspendisse augue mauris, scelerisque eget diam vitae, porttitor mollis libero. Vestibulum euismod, dui ac ultrices laoreet, sapien sapien vehicula sem, eu aliquet nisl leo lacinia sem. Nam ac scelerisque leo. Maecenas rutrum molestie turpis id accumsan.'),
                                                               ('Etiam lacinia risus nec dui.','Nullam tincidunt leo et pellentesque vestibulum. Maecenas consequat tortor odio, non aliquam libero fringilla id. Suspendisse ut ex vestibulum, tempor ligula non, molestie ligula. Etiam cursus porttitor convallis. Pellentesque vehicula ante ut commodo maximus. Curabitur et elementum est. Aliquam commodo quam dui, eget cursus purus tristique vitae. Mauris ac posuere turpis. Phasellus ultricies euismod tellus congue viverra. Etiam luctus est quis elementum consequat. Phasellus luctus euismod eros, eget pharetra leo ultrices a. Sed et cursus arcu, non lacinia nunc. Vestibulum tristique ante ultricies semper dignissim. Suspendisse sodales consequat dolor quis tristique. Duis sagittis lorem ac malesuada auctor.'),
                                                               ('Vestibulum vel felis iaculis, consectetur.','Praesent eu lectus at ex posuere aliquam. Pellentesque feugiat diam sed dui eleifend ultricies. Fusce at aliquam neque, nec consequat tortor. Suspendisse faucibus lorem libero, et ornare elit vehicula non. Vivamus eu hendrerit odio. Nunc luctus magna sed sapien dapibus, ut accumsan ipsum varius. Vestibulum tempus, nulla eu rutrum tincidunt, justo eros cursus dolor, at lacinia diam sem faucibus ipsum. Morbi sit amet egestas erat, id condimentum enim.');
